# AI Code Review Rules для проекта
# Этот файл нужно скопировать в корень вашего GitLab репозитория

project_context:
  name: "AI Review Demo"
  type: "Demo Project"
  tech_stack:
    - Python
    - FastAPI
    - SQLite
  description: "Демонстрационный проект для AI Code Review Assistant"

# Правила безопасности
security_rules:
  - "Запрещены хардкод пароли и API ключи"
  - "Все SQL запросы должны использовать параметризацию или ORM"
  - "Обязательная валидация всех входных данных"
  - "Используйте environment variables для чувствительных данных"
  - "Логирование не должно содержать персональные данные"

# Банковские требования (для реальных проектов ForteBank)
banking_requirements:
  - "Обязательное логирование всех транзакций"
  - "Обработка ошибок с откатом транзакций (rollback)"
  - "Соответствие PCI DSS стандартам"
  - "Двухфакторная аутентификация для критических операций"
  - "Шифрование чувствительных данных"
  - "Аудит доступа к данным клиентов"

# Стиль кода
code_style:
  - "Используйте type hints в Python"
  - "Docstrings для всех публичных функций и классов"
  - "Максимальная длина строки: 100 символов"
  - "Следуйте PEP 8"
  - "Осмысленные имена переменных и функций"

# Best practices
best_practices:
  - "Разделение на слои: routes, services, repositories"
  - "Dependency Injection через FastAPI"
  - "Асинхронные операции где возможно"
  - "Обработка исключений с понятными сообщениями"
  - "Юнит-тесты для бизнес-логики"

# Производительность
performance:
  - "Избегайте N+1 запросов к БД"
  - "Используйте индексы для частых запросов"
  - "Кэширование для статических данных"
  - "Pagination для больших списков"

# Кастомные правила проекта
custom_rules:
  - "Все API endpoints должны возвращать единообразный формат ответа"
  - "Версионирование API через URL (например: /api/v1/)"
  - "Обязательная документация OpenAPI/Swagger"
  - "Rate limiting для публичных endpoints"

# Автоматические действия
auto_actions:
  min_score_for_approval: 8.5  # Минимальный score для автоапрува
  auto_label: true  # Автоматически добавлять метки
  notify_on_critical: true  # Уведомлять при критических проблемах
